Linear regression and practical implementation

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline 
import seaborn as sns

In [2]:
from sklearn.datasets import fetch_openml
boston = fetch_openml(name = 'boston', version = 1, as_frame = True , parser ='pandas')

In [3]:
boston

{'data':         CRIM    ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD    TAX  \
 0    0.00632  18.0   2.31    0  0.538  6.575  65.2  4.0900   1  296.0
 1    0.02731   0.0   7.07    0  0.469  6.421  78.9  4.9671   2  242.0
 2    0.02729   0.0   7.07    0  0.469  7.185  61.1  4.9671   2  242.0
 3    0.03237   0.0   2.18    0  0.458  6.998  45.8  6.0622   3  222.0
 4    0.06905   0.0   2.18    0  0.458  7.147  54.2  6.0622   3  222.0
 ..       ...   ...    ...  ...    ...    ...   ...     ...  ..    ...
 501  0.06263   0.0  11.93    0  0.573  6.593  69.1  2.4786   1  273.0
 502  0.04527   0.0  11.93    0  0.573  6.120  76.7  2.2875   1  273.0
 503  0.06076   0.0  11.93    0  0.573  6.976  91.0  2.1675   1  273.0
 504  0.10959   0.0  11.93    0  0.573  6.794  89.3  2.3889   1  273.0
 505  0.04741   0.0  11.93    0  0.573  6.030  80.8  2.5050   1  273.0

      PTRATIO       B  LSTAT
 0       15.3  396.90   4.98
 1       17.8  396.90   9.14
 2       17.8  392.83   4.03
 3       18.7  394.63   2.94
 4       18.7  396.90   5.33
 ..       ...     ...    ...
 501     21.0  391.99   9.67
 502     21.0  396.90   9.08
 503     21.0  396.90   5.64
 504     21.0  393.45   6.48
 505     21.0  396.90   7.88

 [506 rows x 13 columns],
 'target': 0      24.0
 1      21.6
 2      34.7
 3      33.4
 4      36.2
        ...
 501    22.4
 502    20.6
 503    23.9
 504    22.0
 505    11.9
 Name: MEDV, Length: 506, dtype: float64,
 'frame':         CRIM    ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD    TAX  \
 0    0.00632  18.0   2.31    0  0.538  6.575  65.2  4.0900   1  296.0
 1    0.02731   0.0   7.07    0  0.469  6.421  78.9  4.9671   2  242.0
 2    0.02729   0.0   7.07    0  0.469  7.185  61.1  4.9671   2  242.0
 3    0.03237   0.0   2.18    0  0.458  6.998  45.8  6.0622   3  222.0
 4    0.06905   0.0   2.18    0  0.458  7.147  54.2  6.0622   3  222.0
 ..       ...   ...    ...  ...    ...    ...   ...     ...  ..    ...
 501  0.06263   0.0  11.93    0  0.573  6.593  69.1  2.4786   1  273.0
 502  0.04527   0.0  11.93    0  0.573  6.120  76.7  2.2875   1  273.0
 503  0.06076   0.0  11.93    0  0.573  6.976  91.0  2.1675   1  273.0
 504  0.10959   0.0  11.93    0  0.573  6.794  89.3  2.3889   1  273.0
 505  0.04741   0.0  11.93    0  0.573  6.030  80.8  2.5050   1  273.0

      PTRATIO       B  LSTAT  MEDV
 0       15.3  396.90   4.98  24.0
 1       17.8  396.90   9.14  21.6
 2       17.8  392.83   4.03  34.7
 3       18.7  394.63   2.94  33.4
 4       18.7  396.90   5.33  36.2
 ..       ...     ...    ...   ...
 501     21.0  391.99   9.67  22.4
 502     21.0  396.90   9.08  20.6
 503     21.0  396.90   5.64  23.9
 504     21.0  393.45   6.48  22.0
 505     21.0  396.90   7.88  11.9

 [506 rows x 14 columns],
 'categories': None,
 'feature_names': ['CRIM',
  'ZN',
  'INDUS',
  'CHAS',
  'NOX',
  'RM',
  'AGE',
  'DIS',
  'RAD',
  'TAX',
  'PTRATIO',
  'B',
  'LSTAT'],
 'target_names': ['MEDV'],
 'DESCR': "**Author**:   \n**Source**: Unknown - Date unknown  \n**Please cite**:   \n\nThe Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic\nprices and the demand for clean air', J. Environ. Economics & Management,\nvol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics\n...', Wiley, 1980.   N.B. Various transformations are used in the table on\npages 244-261 of the latter.\nVariables in order:\nCRIM     per capita crime rate by town\nZN       proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS    proportion of non-retail business acres per town\nCHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\nNOX      nitric oxides concentration (parts per 10 million)\nRM       average number of rooms per dwelling\nAGE      proportion of owner-occupied units built prior to 1940\nDIS      weighted distances to five Boston employment centres\nRAD      index of accessibility to radial highways\nTAX      full-value property-tax rate per $10,000\nPTRATIO  pupil-teacher ratio by town\nB        1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT    % lower status of the population\nMEDV     Median value of owner-occupied homes in $1000's\n\n\nInformation about the dataset\nCLASSTYPE: numeric\nCLASSINDEX: last\n\nDownloaded from openml.org.",
 'details': {'id': '531',
  'name': 'boston',
  'version': '1',
  'description_version': '1',
  'format': 'ARFF',
  'creator': ['D. and Rubinfeld', "D.L. 'Hedonic"],
  'collection_date': '1978',
  'upload_date': '2014-09-29T00:08:07',
  'language': 'English',
  'licence': 'Public',
  'url': 'https://openml.org/data/v1/download/52643/boston.arff',
  'parquet_url': 'https://data.openml.org/datasets/0000/0531/dataset_531.pq',
  'file_id': '52643',
  'default_target_attribute': 'MEDV',
  'tag': ['Data Science',
   'Housing Economics',
   'Kaggle',
   'OpenML-Reg19',
   'study_130',
   'Urban Studies'],
  'visibility': 'public',
  'status': 'active',
  'processing_date': '2020-11-20 20:16:37',
  'md5_checksum': 'cdd361fb886627eaa80c92f90d0610cc'},
 'url': 'https://www.openml.org/d/531'}

In [4]:
df = boston.frame  
#for organise in proper frame

In [5]:
df.head() # for first five data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [6]:
df['price'] = boston.target
df.head()  
#adding another price column as taget

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV,price
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2,36.2

dividing the data set into dependent(price ) and independent(other then price column) features

In [7]:
x= df.iloc[: ,:-1] #for removing the last colummn(price)

In [8]:
x.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [9]:
y= df.iloc[ :,-1]

In [10]:
y.head()

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: price, dtype: float64

LINEAR REGRESION

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
#hum cross_val_score function import kar rahe hain.
# ye funcn model ki performance ko multiple time test karta hai
# in other word
#model ko ek hi baar test karne ke bajay , alag alag data parts pe test karta hai ->much reliable result obtaines

#ensure all data is numeric(fix)
x= x.astype(float)
y=y.astype(float)

#initialize and run cross_val_validation
lin_reg = LinearRegression()

#linear regression model ka object create kar raha hai, abhi model train nahi hua hai , sirf ready hai

mse = cross_val_score(lin_reg, x,y, scoring= 'neg_mean_squared_error', cv=5)
print(mse)

# scoring do not return negative value
# cv=5 , 5 time fold cross validation
# data ko 5 parts me divide karega '; 4 parts -> training and 1 part -> testing
# ye rocess 5 baar repeat hoga

[-1.77137943e-28 -6.49802692e-28 -4.43761596e-28 -9.99229020e-28
 -4.15597700e-27]

In [15]:
mean_mse =np.mean(mse)
print("MSE core per fold:", mse)
print ( ' average negative mse', mean_mse)

MSE core per fold: [-1.77137943e-28 -6.49802692e-28 -4.43761596e-28 -9.99229020e-28
 -4.15597700e-27]
 average negative mse -1.2851816492468566e-27

In [17]:
from sklearn.model_selection import train_test_split

x_train , x_test, y_train, y_test = train_test_split(x,y, test_size =0.2 , random_state =42)
#test size =0.2 -> 20% of data onlyfor testing and remaining are for training
#random_state =42

#random_state=42 is a seed value that makes randomness reproducible — every time you run the code, you get the same "random" split/shuffle instead of a different one each run
lin_reg.fit(x_train, y_train) # training data

LinearRegression()

In [18]:
prediction =lin_reg.predict(x_test)

In [19]:
print (prediction)

[23.6 32.4 13.6 22.8 16.1 20.  17.8 14.  19.6 16.8 21.5 18.9  7.  21.2
 18.5 29.8 18.8 10.2 50.  14.1 25.2 29.1 12.7 22.4 14.2 13.8 20.3 14.9
 21.7 18.3 23.1 23.8 15.  20.8 19.1 19.4 34.7 19.5 24.4 23.4 19.7 28.2
 50.  17.4 22.6 15.1 13.1 24.2 19.9 24.  18.9 35.4 15.2 26.5 43.5 21.2
 18.4 28.5 23.9 18.5 25.  35.4 31.5 20.2 24.1 20.  13.1 24.8 30.8 12.7
 20.  23.7 10.8 20.6 20.8  5.  20.1 48.5 10.9  7.  20.9 17.2 20.9  9.7
 19.4 29.  16.4 25.  25.  17.1 23.2 10.4 19.6 17.2 27.5 23.  50.  17.9
  9.6 17.2 22.5 21.4]

In [21]:
# compare real and predicted value
import pandas as pd
comparison_df = pd.DataFrame({ 'actual':y_test, 'prediction':prediction})
print(comparison_df.head())

     actual  prediction
173    23.6        23.6
274    32.4        32.4
491    13.6        13.6
72     22.8        22.8
452    16.1        16.1

checking the accuracy of the model

In [25]:
from  sklearn import metrics
import numpy as np

#1. r-square , best possible score is 1.0
r2 = metrics.r2_score(y_test, prediction)

#2. mean absolute error (average error in price unit)
mae = metrics.mean_absolute_error(y_test, prediction)

#3. root mean square error(standard deviation of prediction error)
rmse = np.sqrt(metrics.mean_squared_error(y_test, prediction))

print(f"R-square score :{r2:.4f}")
print(f"Mean absolute error(MAE) :{mae:.4f}")
print(f"root mean square error (RMSE): {rmse:.4f}")

R-square score :1.0000
Mean absolute error(MAE) :0.0000
root mean square error (RMSE): 0.0000

| Metric | Kya batata hai | Goal |
|--------|----------------|------|
| **R²** | Features price ko kitna achha explain kar rahe | Jitna 1 ke paas, utna achha |
| **MAE** | Average kitna galat predict ho raha | Jitna 0 ke paas, utna achha |
| **RMSE** | Badi galtiyon ko zyada punish karta | Jitna 0 ke paas, utna achha |

Ridge regression (advance version of linear)

In [26]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

ridge = Ridge()
#converting ridge into object

In [28]:
param = {'alpha':[1e-15, 1e-10,1e-8,1e-3 ,1e-2,1,5,10,20]}

ridge_regressor = GridSearchCV(ridge, param, scoring ='neg_mean_squared_error',cv= 5)
ridge_regressor.fit(x,y)
#1e-15  ,means 15 time zero before appearing one

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.001, 0.01, 1, 5, 10,
                                   20]},
             scoring='neg_mean_squared_error')

In [30]:
print(ridge_regressor.best_params_)
print(ridge_regressor.best_score_)
#best params ans score for finding error

{'alpha': 1e-15}
-4.614807197586796e-29

In [31]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV

lasso = Lasso()
params = {'alpha':[1e-15, 1e-10,1e-8,1e-3 ,1e-2,1,5,10,20]}

lasso_regressor = GridSearchCV(lasso, params, scoring ='neg_mean_squared_error',cv= 5)
lasso_regressor.fit(x,y)

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.001, 0.01, 1, 5, 10,
                                   20]},
             scoring='neg_mean_squared_error')

#lasso regression

In [32]:
print(lasso_regressor.best_params_)
print(lasso_regressor.best_score_)

{'alpha': 1e-08}
-1.0626085889405631e-07

# checking for the accuracy of model

In [36]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
# standardScaler and r2_score are used for measuring of the accuracy of the lasso , ridge
# Ensure data is numeric
x = x.astype(float)
y = y.astype(float)

# 1. Scale the features (Essential for Ridge and Lasso)
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

# 2. Split into Training and Testing sets
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.2, random_state=42)

# Linear regression

In [38]:
from sklearn.linear_model import LinearRegression
#initialize
lin_reg = LinearRegression()
#train
lin_reg.fit(x_train, y_train)

#predicate and calculate accracy
#train
lin_pred = lin_reg.predict(x_test)
lin_acc = r2_score(y_test, lin_pred)*100

print(f"linear regression accuracy: {lin_acc:.2f}%")

linear regression accuracy: 100.00%

# Ridge regression

In [40]:
from sklearn.linear_model import Ridge

# alpha is the penality strength (higher alpha = more restriction)
#ready ridge
ridge_reg = Ridge(alpha=10.0)
#train
ridge_reg.fit(x_train, y_train)

#predict and calculate accuracy
ridge_pred = ridge_reg.predict(x_test)
# for accuracy
ridge_acc = r2_score(y_test ,ridge_pred)*100

print(f"Ridge regression accuracy:{ridge_acc:.2f}%")

Ridge regression accuracy:99.76%

# Lasso regression accuracy

In [42]:
from sklearn.linear_model import Lasso
# alpha =0.1 is a common starting point for lasso
lasso_reg = Lasso(alpha =0.1)
#train
lasso_reg.fit(x_train,y_train)
#predict and accuracy
#testing of model
lasso_pred = lasso_reg.predict(x_test)
#accuracy
lasso_acc = r2_score(y_test, lasso_pred)*100

print(f"lasso regression accuracy: {lasso_acc:.2f}%")

lasso regression accuracy: 99.99%